import Head from "next/head";
import { useGetPokemonQuery } from "../store/pokemonApi/pokemonApi";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { data } = useGetPokemonQuery();
  console.log(data);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ marginTop: 200, marginLeft: 200 }}>
        <input type="text" style={{ padding: 20 }} />
        <button style={{ padding: 20 }}>Submit</button>
      </div>
    </div>
  );
}
